In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train,y_train),(x_test,y_test) = mnist.load_data()
x_train,x_test = x_train/255.0, x_test/255.0

11493376/11490434 [==============================] - 0s 0us/step


In [3]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.02538981,  0.26798335, -0.49703294, -0.09059842, -0.37187347,
         0.01851152,  0.17230862, -1.0127962 , -0.05784771,  0.70926696]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.1016523 , 0.129561  , 0.06028815, 0.09051993, 0.06832632,
        0.10095551, 0.1177398 , 0.03599472, 0.09353361, 0.20142868]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1],predictions).numpy()

2.2930753

In [8]:
model.compile(optimizer='adam',loss=loss_fn,metrics=['accuracy'])

In [9]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2945 - accuracy: 0.9154
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1431 - accuracy: 0.9577
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1079 - accuracy: 0.9676
Epoch 4/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0875 - accuracy: 0.9735
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0751 - accuracy: 0.9764


In [10]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 0s - loss: 0.0795 - accuracy: 0.9749


[0.07947935163974762, 0.9749000072479248]

In [11]:
probability_Model = tf.keras.Sequential([
              model,tf.keras.layers.Softmax()
])

In [12]:
probability_Model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.50385677e-08, 2.04000195e-09, 3.61118964e-06, 7.55866640e-05,
        3.81258303e-10, 5.79188850e-07, 2.46682210e-12, 9.99914050e-01,
        8.89121736e-08, 6.09936296e-06],
       [1.42100305e-08, 4.04918130e-04, 9.99589145e-01, 5.62530886e-06,
        1.37268965e-14, 4.01274569e-08, 1.38832119e-08, 6.89061709e-13,
        1.78734240e-07, 2.55226326e-11],
       [3.19104686e-07, 9.96939421e-01, 1.69910796e-04, 5.44776958e-06,
        3.50519767e-05, 2.64554001e-06, 1.80728227e-06, 2.60010152e-03,
        2.44231429e-04, 1.01547710e-06],
       [9.99977589e-01, 1.03954848e-11, 1.06687810e-06, 1.21426302e-09,
        5.69972070e-09, 1.73045773e-08, 1.87637725e-05, 2.66701477e-07,
        1.21104804e-09, 2.33980018e-06],
       [7.94698553e-06, 3.67400389e-07, 9.55880023e-06, 8.48221404e-08,
        9.80192482e-01, 3.04671033e-07, 1.93200185e-06, 2.27325127e-05,
        1.38658766e-06, 1.97631717e-02]], dtype=float32)>